/*
 * This file is generated by AI (https://claude.ai/).
 */

#ifndef UNITY_CONFIG_H
#define UNITY_CONFIG_H

// Unity configuration for AVR embedded testing

// Define Unity output method
#define UNITY_OUTPUT_CHAR(c) putchar(c)
#define UNITY_OUTPUT_FLUSH() fflush(stdout)

// Enable floating point support if needed
#define UNITY_INCLUDE_FLOAT
#define UNITY_INCLUDE_DOUBLE

// Enable additional Unity features
#define UNITY_SUPPORT_64

// AVR-specific mock functions and definitions
#ifdef UNIT_TEST

#include <stdio.h>
#include <stdint.h>
#include <stdbool.h>

// Mock AVR register values - initialize to realistic defaults
static uint8_t mock_DDRB = 0x00;   // Data Direction Register B
static uint8_t mock_DDRC = 0x00;   // Data Direction Register C  
static uint8_t mock_DDRD = 0x00;   // Data Direction Register D
static uint8_t mock_PORTB = 0x00;  // Port B Data Register
static uint8_t mock_PORTC = 0x00;  // Port C Data Register
static uint8_t mock_PORTD = 0x00;  // Port D Data Register
static uint8_t mock_PINB = 0x00;   // Port B Input Pins
static uint8_t mock_PINC = 0x00;   // Port C Input Pins
static uint8_t mock_PIND = 0x00;   // Port D Input Pins

// Timer/Counter registers
static uint8_t mock_TCCR0A = 0x00;
static uint8_t mock_TCCR0B = 0x00;
static uint8_t mock_TCCR1A = 0x00;
static uint8_t mock_TCCR1B = 0x00;
static uint8_t mock_TCCR2A = 0x00;
static uint8_t mock_TCCR2B = 0x00;
static uint8_t mock_TCNT0 = 0x00;
static uint16_t mock_TCNT1 = 0x0000;
static uint8_t mock_TCNT2 = 0x00;
static uint8_t mock_OCR0A = 0x00;
static uint8_t mock_OCR0B = 0x00;
static uint16_t mock_OCR1A = 0x0000;
static uint16_t mock_OCR1B = 0x0000;
static uint8_t mock_OCR2A = 0x00;
static uint8_t mock_OCR2B = 0x00;

// ADC registers
static uint8_t mock_ADMUX = 0x00;
static uint8_t mock_ADCSRA = 0x00;
static uint16_t mock_ADC = 0x0000;

// USART registers
static uint8_t mock_UCSR0A = 0x20;  // UDRE0 bit set (ready to transmit)
static uint8_t mock_UCSR0B = 0x00;
static uint8_t mock_UCSR0C = 0x06;  // Default: 8-bit, no parity, 1 stop bit
static uint16_t mock_UBRR0 = 0x0000;
static uint8_t mock_UDR0 = 0x00;

// Interrupt registers
static uint8_t mock_SREG = 0x00;
static uint8_t mock_TIMSK0 = 0x00;
static uint8_t mock_TIMSK1 = 0x00;
static uint8_t mock_TIMSK2 = 0x00;
static uint8_t mock_PCICR = 0x00;
static uint8_t mock_PCMSK0 = 0x00;
static uint8_t mock_PCMSK1 = 0x00;
static uint8_t mock_PCMSK2 = 0x00;

// Define register macros that point to our mock variables
#define DDRB mock_DDRB
#define DDRC mock_DDRC  
#define DDRD mock_DDRD
#define PORTB mock_PORTB
#define PORTC mock_PORTC
#define PORTD mock_PORTD
#define PINB mock_PINB
#define PINC mock_PINC
#define PIND mock_PIND

// Timer registers
#define TCCR0A mock_TCCR0A
#define TCCR0B mock_TCCR0B
#define TCCR1A mock_TCCR1A
#define TCCR1B mock_TCCR1B
#define TCCR2A mock_TCCR2A
#define TCCR2B mock_TCCR2B
#define TCNT0 mock_TCNT0
#define TCNT1 mock_TCNT1
#define TCNT2 mock_TCNT2
#define OCR0A mock_OCR0A
#define OCR0B mock_OCR0B
#define OCR1A mock_OCR1A
#define OCR1B mock_OCR1B
#define OCR2A mock_OCR2A
#define OCR2B mock_OCR2B

// ADC registers
#define ADMUX mock_ADMUX
#define ADCSRA mock_ADCSRA
#define ADC mock_ADC

// USART registers  
#define UCSR0A mock_UCSR0A
#define UCSR0B mock_UCSR0B
#define UCSR0C mock_UCSR0C
#define UBRR0 mock_UBRR0
#define UDR0 mock_UDR0

// Interrupt registers
#define SREG mock_SREG
#define TIMSK0 mock_TIMSK0
#define TIMSK1 mock_TIMSK1
#define TIMSK2 mock_TIMSK2
#define PCICR mock_PCICR
#define PCMSK0 mock_PCMSK0
#define PCMSK1 mock_PCMSK1
#define PCMSK2 mock_PCMSK2

// Common bit definitions for ATmega328P
// Port bit numbers
#define PB0 0
#define PB1 1
#define PB2 2
#define PB3 3
#define PB4 4
#define PB5 5
#define PB6 6
#define PB7 7

#define PC0 0
#define PC1 1
#define PC2 2
#define PC3 3
#define PC4 4
#define PC5 5
#define PC6 6

#define PD0 0
#define PD1 1
#define PD2 2
#define PD3 3
#define PD4 4
#define PD5 5
#define PD6 6
#define PD7 7

// Timer bit definitions (common ones)
#define CS00 0
#define CS01 1
#define CS02 2
#define WGM00 0
#define WGM01 1
#define WGM02 3
#define COM0A0 6
#define COM0A1 7
#define COM0B0 4
#define COM0B1 5

// ADC bit definitions
#define ADEN 7
#define ADSC 6
#define ADATE 5
#define ADIF 4
#define ADIE 3
#define ADPS2 2
#define ADPS1 1
#define ADPS0 0

// USART bit definitions
#define RXC0 7
#define TXC0 6
#define UDRE0 5
#define FE0 4
#define DOR0 3
#define UPE0 2
#define U2X0 1
#define MPCM0 0

#define RXCIE0 7
#define TXCIE0 6
#define UDRIE0 5
#define RXEN0 4
#define TXEN0 3
#define UCSZ02 2
#define RXB80 1
#define TXB80 0

// Mock utility functions for testing
static inline void reset_avr_mocks(void) {
    mock_DDRB = 0x00;
    mock_DDRC = 0x00;
    mock_DDRD = 0x00;
    mock_PORTB = 0x00;
    mock_PORTC = 0x00;
    mock_PORTD = 0x00;
    mock_PINB = 0x00;
    mock_PINC = 0x00;
    mock_PIND = 0x00;
    mock_TCCR0A = 0x00;
    mock_TCCR0B = 0x00;
    mock_TCCR1A = 0x00;
    mock_TCCR1B = 0x00;
    mock_TCCR2A = 0x00;
    mock_TCCR2B = 0x00;
    mock_TCNT0 = 0x00;
    mock_TCNT1 = 0x0000;
    mock_TCNT2 = 0x00;
    mock_ADMUX = 0x00;
    mock_ADCSRA = 0x00;
    mock_ADC = 0x0000;
    mock_UCSR0A = 0x20;
    mock_UCSR0B = 0x00;
    mock_UCSR0C = 0x06;
    mock_UBRR0 = 0x0000;
    mock_SREG = 0x00;
}

// Mock interrupt functions
#define sei() do { mock_SREG |= (1 << 7); } while(0)
#define cli() do { mock_SREG &= ~(1 << 7); } while(0)

// Mock delay functions
static inline void _delay_ms(double ms) {
    printf("Mock: _delay_ms(%.2f)\n", ms);
    // Uncomment for actual delays in tests
    // usleep((unsigned long)(ms * 1000));
}

static inline void _delay_us(double us) {
    printf("Mock: _delay_us(%.2f)\n", us);
    // Uncomment for actual delays in tests
    // usleep((unsigned long)us);
}

// Time tracking for millis simulation
static uint32_t mock_millis_counter = 0;
static inline uint32_t millis_mock(void) {
    return mock_millis_counter;
}

static inline void advance_millis(uint32_t ms) {
    mock_millis_counter += ms;
}

// Helper functions to check register states in tests
static inline bool is_bit_set(uint8_t reg, uint8_t bit) {
    return (reg & (1 << bit)) != 0;
}

static inline bool is_pin_output(uint8_t port, uint8_t pin) {
    switch(port) {
        case 'B': return is_bit_set(mock_DDRB, pin);
        case 'C': return is_bit_set(mock_DDRC, pin);
        case 'D': return is_bit_set(mock_DDRD, pin);
        default: return false;
    }
}

static inline bool is_pin_high(uint8_t port, uint8_t pin) {
    switch(port) {
        case 'B': return is_bit_set(mock_PORTB, pin);
        case 'C': return is_bit_set(mock_PORTC, pin);
        case 'D': return is_bit_set(mock_PORTD, pin);
        default: return false;
    }
}

#endif // UNIT_TEST

#endif // UNITY_CONFIG_H
